### ISSUE TITLE
Password hashing returns different results for 64bit dart compiler

### ISSUE THREAD

**Issue by jeroentrappers** [Erly/dbcrypt#4]
Hi, I'm using this library in a **flutter** app. It works fine when building an APK. However with recent changes to Android store, a 64bit version is also required. I've started with the conversion to Android Application Bundle (AAB) and ran into an issue where output differs between these versions.

For example:
APK:
`DBCrypt result: $2b$06$C6UzMDM.H6dfI/f/IKxGhuVi1DmY0ZHRIOlDzy68M6XV7JwYKuDem`

AAB:
`DBCrypt result: $2b$06$C6UzMDM.H6dfI/f/IKxGhuct16o.zHWI649k44CjX4q927Dr/1iaS`

for this call: 

`var result = new DBCrypt().hashpw(r'3282aae5-f104-4639-88a3-3af9a1efb069', r'$2b$06$C6UzMDM.H6dfI/f/IKxGhu');`
`log.fine("DBCrypt result: $result");`

I've also tried the unchanged test suite with the dart aot compiler, and get a similar error
`dart2aot dbcrypt_test.dart out`
```± % dartaotruntime out                                                                                                                                            !7356
00:00 +0: Hash password
00:00 +0 -1: Hash password [E]
  Expected: '$2a$06$DCq7YPn5Rq63x1Lad4cll.TV4S6ytwfsfvkgY8jIucDrjc8deX1s.'
    Actual: '$2a$06$DCq7YPn5Rq63x1Lad4cll.orYsuQL82N1BwdzuqOJ5NXWjEuHrO.u'
     Which: is different.
            Expected: ... x1Lad4cll.TV4S6ytwfs ...
              Actual: ... x1Lad4cll.orYsuQL82N ...
                                    ^
             Differ at offset 29
```

Do you have any clue as to where this difference might come from?
Kind regards,
Jeroen

**Comment by Erly** [comment]
Hi @jeroentrappers thanks for opening the issue. After upgrading to Dart 2.4.1 the tests with AOT pass again, it seems it was related to  #https://github.com/dart-lang/sdk/issues/37551

Can you try your AAB app with Dart 2.4.1 to see if the error is fixed there too?

**Comment by Erly** [comment]
Yeah, it's because Flutter 1.7.8 uses Dart 2.4.0 which has the bug I stated earlier. Until the flutter team makes a new stable release with Dart 2.4.1 the only way to use dbcrypt with flutter is to use an old version of flutter with an older version of Dart or upgrade to the dev channel (if/when they use a Dart version with the bug fix)
