### ISSUE TITLE
Bad number of Rounds Exception thrown

### ISSUE THREAD

**Issue by joardar-aditya** [Erly/dbcrypt#5]
Generating salts with the number of rounds less than 4 generating bad number of rounds. Please if possible extend it! for different use cases!

**Comment by Erly** [comment]
Hi joardar-aditya, sorry for not answering before, a cost factor of 4 is already a incredibly low number for today's standards and a password could be easily brute forced with that number. The recommendation is to use a cost factor that takes ~250ms per password, what use case requires a number lower than 4?
